# https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key
resource "tls_private_key" "private_key" {
  #
  # ⚠ IMPORTANT SECURITY ISSUE ⚠
  # The private key generated by this resource will be stored unencrypted in your Terraform state file. 
  # Use of this resource for production deployments is not recommended. Instead, generate a private key
  # file outside of Terraform and distribute it securely to the system where Terraform will be run.
  #
  algorithm   = "ECDSA"
  ecdsa_curve = "P384"
}

# https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file
resource "local_file" "ssh_private_key" {
  content  = tls_private_key.private_key.private_key_openssh
  filename = local.ssh_private_key
  # http://www.permissionscalculator.com/ 
  # -r--------
  file_permission = "0400"
}

resource "local_file" "ssh_public_key" {
  content  = tls_private_key.private_key.public_key_openssh
  filename = local.ssh_public_key
  # http://www.permissionscalculator.com/ 
  # -rw-r--r--
  file_permission = "0644"
}