all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: vagrant
  hosts:
%{ for ip in all_ips ~}
    ${ip}:
%{ endfor ~}
  children:
    monitoring:
      hosts:
%{ for ip in monitoring_ips ~}
        ${ip}:
%{ endfor ~}
